#' Bootstrap parameters for distributed DAP/MAP market model
#'
#' @seealso \code{\link{bootstrap.demand}}, \code{\link{bootstrap.supply}}, \code{\link{bootstrap.costs}}
#' @docType package
#' @name dapmap.parameters
NULL

#' Boootstrap samples of DAP/MAP demand by region and scenario
#'
#' This compilation provides bootstrap samples for regional demand in the distributed DAP/MAP market model.
#' The compilation covers 9 regions and FAO "Business as Usual" and "Stratified Societies" scenarios for crop production in year 2030.
#' Demand values are generated by region and scenario using instrumental variable regression model with wild unrestricted residual bootstrap (Davidson and MacKinnon 2010).
#'
#' Metric kilotonnes of P2O5 per annum are used for volumes throughout this compilation.
#' 
#' The following definitions apply: DAP - diammonium phosphate, MAP - monoammonium phosphate.
#'
#' Regional classification includes: Africa, East Asia, Eastern Europe and Central Asia, Latin America, North America, Oceania, South Asia, Western and Central Europe, and Western Asia.
#' 
#' Regression variables include:
#' \itemize{
#'   \item z: phosphorus use in selected crops production (instrument),
#'   \item x: total phosphorus use in agriculture (endogenous variable in the reduced-form equation),
#'   \item y: DAP/MAP consumption (endogenous variable in the structural equation).
#' }
#' 
#' The data in \code{dapmap.markets} and \code{puse} packages is used for estimation.
#' Original values for years 2007-2017 are smoothed using central moving average with span 3.
#'
#' The bootstrap data-generating process includes the following steps:
#' \enumerate{
#'   \item Estimate original regression coefficients and residuals using two-stage least squares and smoothed data for years 2007-2017 (9 observations): regress x on z, regress y on prediced x.
#'   \item Resample with replacement disturbance terms in reduced-form and structural equations using wild unrestricted bootstrap with Rademacher distribution on centered and corrected residuals.
#'   \item Compile new bootstrap sample from equations with instrument, bootstrap residuals and estimated coefficients.
#'   \item Estimate bootstrap coefficients and residuals using two-stage least squares and new bootstrap sample. 
#'   \item Generate new disturbance terms as in step 2.
#'   \item Estimate DAP/MAP consumption in 2030 as a predicted value from the model with bootstrap coefficients from step 4 and new bootstrap residuals from step 5.
#'   \item Repeat steps 2-6 1000 times and collect values in the bootstrap sample of DAP/MAP demand.
#' }
#'
#' In total, the bootstrap data-generating process for DAP/MAP demand is run 18 times to obtain samples for each region and scenario.
#'
#' @docType data
#'
#' @references 
#' \itemize{
#'   \item Davidson, R., & MacKinnon, J. (2010). Wild Bootstrap for IV Regression. Journal of Business & Economic Statististics, 28(1):128-144.
#' }
"bootstrap.demand"

#' Boootstrap samples of DAP/MAP supply by supplier and scenario
#'
#' This compilation provides bootstrap samples for producers' supply in the distributed DAP/MAP market model.
#' The compilation covers 5 suppliers and FAO "Business as Usual" and "Stratified Societies" scenarios for crop production in year 2030.
#' Supply values are generated by supplier and scenario using wild bootstrap (Davidson and MacKinnon 2010).
#' It is assumed that international suppliers aim to maintain their shares in global market supply in 2030 by adding capacity as necessary ("Commodity Classic" scenario in IFA 2018).
#'
#' Metric kilotonnes of P2O5 per annum are used for volumes throughout this compilation.
#' 
#' The following definitions apply: DAP - diammonium phosphate, MAP - monoammonium phosphate.
#'
#' This compilation covers the following phosphate companies and groups of companies:
#' \itemize{
#'   \item Chinese exporters
#'   \item Maaden https://www.maaden.com.sa/
#'   \item Mosaic http://www.mosaicco.com/
#'   \item PhosAgro/EuroChem https://phosagro.com/, https://www.eurochemgroup.com/
#'   \item OCP https://www.ocpgroup.ma/
#' }
#'
#' The data in \code{dapmap.markets} package for years 2013-2017 is used for estimation. \code{bootstrap.demand} is used for projection.
#'
#' The bootstrap data-generating process includes the following steps:
#' \enumerate{
#'   \item Estimate mean market share and deviations from the mean using data for years 2007-2017 by supplier (25 observations in total).
#'   \item Resample with replacement from the joint sample of centered deviations from the mean using wild bootstrap with Rademacher distribution .
#'   \item Compile new bootstrap sample of market shares from observed means and bootstrap deviations from the mean.
#'   \item Estimate DAP/MAP supply from bootstrap market shares and world demand in \code{bootstrap.demand}.
#'   \item Repeat steps 2-4 1000 times and collect values in the bootstrap sample of DAP/MAP supply.
#' }
#'
#' In total, the bootstrap data-generating process for DAP/MAP supply is run 2 times to obtain samples for each scenario.
#'
#' @docType data
#'
#' @references 
#' \itemize{
#'   \item Davidson, R., & MacKinnon, J. (2010). Wild Bootstrap for IV Regression. Journal of Business & Economic Statististics, 28(1):128-144.
#'   \item IFA (2018). IFA 2030 Scenarios. Downloaded from https://www.fertilizer.org/Public/About_IFA/IFA2030.aspx
#' }
"bootstrap.supply"

#' Boootstrap samples of DAP/MAP costs by supplier, region and scenario
#'
#' This compilation provides bootstrap samples for suppliers' trade costs in the distributed DAP/MAP market model.
#' The compilation covers 5 suppliers, 9 regions and FAO "Business as Usual" and "Stratified Societies" scenarios for crop production in year 2030.
#' Cost values are generated by supplier, region and scenario using regression model with wild unrestricted residual bootstrap (Davidson and MacKinnon 2010).
#'
#' Values are measured on the [0,1] price/cost scale throughout this compilation.
#' 
#' The following definitions apply: DAP - diammonium phosphate, MAP - monoammonium phosphate.
#'
#' This compilation covers the following phosphate companies and groups of companies:
#' \itemize{
#'   \item Chinese exporters
#'   \item Maaden https://www.maaden.com.sa/
#'   \item Mosaic http://www.mosaicco.com/
#'   \item PhosAgro/EuroChem https://phosagro.com/, https://www.eurochemgroup.com/
#'   \item OCP https://www.ocpgroup.ma/
#' }
#'
#' Regional classification includes: Africa, East Asia, Eastern Europe and Central Asia, Latin America, North America, Oceania, South Asia, Western and Central Europe, and Western Asia.
#'
#' The data on DAP/MAP fertilizer trade volumes in years 2013-2017 in \code{dapmap.markets} package is used for estimation. \code{bootstrap.demand} is used for projection.
#'
#' The data processing of original values into a sample includes the following steps:
#' \enumerate{
#'   \item Filter original data to exclude flows smaller than 1\% of total import flows to a region in the year.
#' Add excluded volume to regional domestic supply. Total consumption by region and year in corrected data will be equal to total consumption in the raw data.
#'   \item Calculate nominal market share in global demand based on the filtered data (by year and region). 
#'   \item Find growth rate of Latin America market share in global demand relative to the share in year 2014 (by year).
#'   \item Find real market share in global demand by dividing the nominal value by the growth rate of Latin America market share (by year and region).
#'   \item Calculate trade cost from the equilibrium volumes for a supplier present on a market with the assumption that trade cost for Latin America market equals 0 (by supplier, region and year).
#'   \item Compose a sample of differences in real market shares relative to base year 2014, 
#' and a sample of differences in trade costs relative to base year 2014 (for years 2015-2017).
#' }
#'
#' The bootstrap data-generating process includes the following steps:
#' \enumerate{
#'   \item Estimate regression coefficients and residuals using least squares on the joint sample: regress differences in trade costs on differences in real market shares.
#'   \item Resample with replacement from centered residuals using wild unrestricted residual bootstrap with Rademacher distribution.
#'   \item Calculate forecast differences in real market shares for year 2030 relative to base year 2014 (by scenario).
#'   \item Estimate differences in trade costs in 2030 as predicted values from the model with forecast differences in real market shares for year 2030 from step 3, 
#' estimated coefficients from step 1 and new bootstrap residuals from step 2.
#'   \item Calculate trade costs in 2030 using the estimated differences from step 4 and reference trade costs in base year 2014. 
#'   \item Repeat steps 2-5 1000 times and collect values in the bootstrap samples of DAP/MAP costs by supplier, region and scenario.
#' }
#'
#' In total, there are 101 observations in the joint sample of differences for regression estimation.
#'
#' @docType data
#'
#' @references 
#' \itemize{
#'   \item Davidson, R., & MacKinnon, J. (2010). Wild Bootstrap for IV Regression. Journal of Business & Economic Statististics, 28(1):128-144.
#' }
"bootstrap.costs"